### PR TITLE
updates to example data files that should work with the theme updates

### PR DESCRIPTION
**Pull request by adf-ncgr**
I haven't tested anything!

### CODE REVIEW

**Comment by sammyjava** [comment]
Ummmm it looks like jekyll-starter-legumeinfo does not have the jekyll-theme-legumeinfo from GitHub as its theme - it's a local theme like the LIS site used to be. You want me to wrangle that? I didn't notice since I always test against my dev jekyll-legumeinfo instance rather than the starter site (which I've never touched, TBH).

**Comment by adf-ncgr** [comment]
Sounds like a question for @alancleary I don't think this would be anything I had touched (and I'm paying half-attention to this at the moment while on an unrelated call...)

**Comment by alancleary** [comment]
> Ummmm it looks like jekyll-starter-legumeinfo does not have the jekyll-theme-legumeinfo from GitHub as its theme - it's a local theme like the LIS site used to be. You want me to wrangle that? I didn't notice since I always test against my dev jekyll-legumeinfo instance rather than the starter site (which I've never touched, TBH).

What do you mean? The theme is a submodule of the starter repo and is specified in `_config.yml`.

**Comment by sammyjava** [comment]
Hrm you're right, I musta had an old/botched copy. Never mind, now testing. :)

**Comment by alancleary** [comment]
This seems to be working with the bug fix introduced in theme PR [#45](https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/45). I'll officially review this PR once that one is merged.

**Review by alancleary — CHANGES_REQUESTED** [review]
I spoke too soon. None of the `genus_resources.yml` files have a `taxid` value so none of the pages generated have any content besides the "no resource data in the Datastore" message.

Not sure how you want to handle this but requiring a `taxid` seems pretty restrictive to me.

**Edit:** Digging in a little deeper, none of the taxa files have a `commonName` field and none of the `species_resources` have a `species` field, so pretty much none of the content would be generated even if the `taxid` values were present. More generally, these data files seem pretty out of sync with what's in the `taxon.html` layout and on LIS. So basically either the data files or the taxon layout need to significantly change.

**Comment by sammyjava** [comment]
Are we deviating for the starter site from the kind of data that is being generated on the jekyll-legumeinfo site? Because that works fine, or at least seems to work fine, other than that warning that I mentioned today, which seems to be new. I ran the data-generating script today on the dev site and it seems to be fine.

**Comment by adf-ncgr** [comment]
No, I think this is my bad. I seem to have a bunch of uncommitted changes to the _data files that are probably the same ones I had originally added under the theme. Stand by.

**Comment by adf-ncgr** [comment]
OK hopefull [e8bebc1](https://github.com/legumeinfo/jekyll-starter-legumeinfo/pull/6/commits/e8bebc15a8bee4275486ab3df49123e8fbc3a92c) did the needful to make everything work. Let me know if not.

**Comment by sammyjava** [comment]
Well I did a clean clone of the starter site along with the theme; switched the starter site to `example_data_update` and switched the theme to `goodbye_data`. Got this, not too unexpected, I think we need that `file_exists` update merged in.
```console
       Jekyll Feed: Generating feed for posts
  Liquid Exception: Liquid syntax error (line 39): Unknown tag 'file_exists' in taxa/arachis/index.html
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/share/gems/gems/liquid-4.0.3/lib/liquid/block.rb:38:in `unknown_tag': Liquid syntax error (line 39): Unknown tag 'file_exists' (Liquid::SyntaxError)
```

**Comment by alancleary** [comment]
> I think we need that file_exists update merged in.

Correct. If you checkout the taxon-file-exists-fix branch as the starter's theme things appear to be working as expected.

**Comment by sammyjava** [comment]
That includes the `goodbye-data` update, though? We've got dueling branches here, I'm testing the `goodbye-data` branch on the theme. Anyway if you like it, approve it.

**Comment by alancleary** [comment]
> That includes the `goodbye-data` update, though? We've got dueling branches here, I'm testing the `goodbye-data` branch on the theme. Anyway if you like it, approve it.

`goodbye_data` was [already merged](https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/43) in the theme and is included in the `taxon-file-exists-fix` PR. I was waiting for you to confirm that the most recent commit to `taxon-file-exists-fix` works for you before merging.

**Review by sammyjava — APPROVED** [review]
Okay, I got it now. `starter:example_data_update` against `theme:taxon-file-exists-fix` works fine.

**Comment by alancleary** [comment]
> Okay, I got it now. `starter:example_data_update` against `theme:taxon-file-exists-fix` works fine.

Thanks for verifying it works; PR merged!

**Review by alancleary — APPROVED** [review]
I pushed a commit that updates the theme so the missing file_exists plugin is no longer an issue. This PR should now work when merged into main.

**Pull request merged**
