### PR TITLE
Updates theme to version 1.0.0

### PR DESCRIPTION
**Pull request by alancleary**
This includes replacing removing pages that are trivial to implement (e.g. contact) and adding pages that demonstrate specific theme functionality (e.g. web components).

### CODE REVIEW

**Comment by svengato** [comment]
It looks like I can delete the untracked `uikit` subdirectory from the (local) theme?

**Comment by alancleary** [comment]
> It looks like I can delete the untracked `uikit` subdirectory from the (local) theme?

Yes. Follow these steps if you want to be sure you're updating the theme correctly: https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/75#issuecomment-1889677040

**Comment by svengato** [comment]
> Yes. Follow these steps if you want to be sure you're updating the theme correctly:

Except `git checkout uikit-updates` is now `git checkout main`.

**Comment by svengato** [comment]
I built the starter site with both `bundle exec jekyll serve` and `docker compose up -d`, it looks fine in both cases. In the former case, it modified my `Gemfile.lock`. Anything special I should look for?

**Comment by alancleary** [comment]
> I built the starter site with both `bundle exec jekyll serve` and `docker compose up -d`, it looks fine in both cases. In the former case, it modified my `Gemfile.lock`. Anything special I should look for?

Can you share the diff on the `Gemfile.lock`? This PR already includes the necessary updates.

**Comment by svengato** [comment]
> Can you share the diff on the `Gemfile.lock`?

Not working now - I think I broke it by running `sudo bundle install`. Any quick fixes for that?

**Comment by svengato** [comment]
Found it in the history -
```
diff --git a/Gemfile.lock b/Gemfile.lock
index f3bdb60..e4cb3aa 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -56,16 +56,16 @@ GEM
     pathutil (0.16.2)
       forwardable-extended (~> 2.6)
     public_suffix (5.0.4)
+    rake (13.1.0)
     rb-fsevent (0.11.2)
     rb-inotify (0.10.1)
       ffi (~> 1.0)
     rexml (3.2.6)
     rouge (4.2.0)
     safe_yaml (1.0.5)
-    sass-embedded (1.69.5-aarch64-linux-gnu)
-      google-protobuf (~> 3.23)
-    sass-embedded (1.69.5-x86_64-linux-gnu)
+    sass-embedded (1.69.5)
       google-protobuf (~> 3.23)
+      rake (>= 13.0.0)
     terminal-table (3.0.2)
       unicode-display_width (>= 1.1.1, < 3)
     unicode-display_width (2.5.0)
```

**Comment by svengato** [comment]
Fixed the problem by
```
bundle config set --local path 'vendor/bundle'
```
and trying again. The diff is the same as above.

**Review by svengato — APPROVED** [review]
It looks fine to me. The `Gemfile.lock` differences were when I built it using `bundle exec jekyll serve`, it is not an issue with Docker, so I will stick to Docker builds from now on.

**Pull request merged**
